version: '3'
services:
  app:
    image: node:8.16.2-jessie
    ports:
      - "3000:3000"
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
